# Triggers ...
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Test Project
        run: npm run test
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build
          
  # Deploy Dev Job
  deploy-dev:
    name: Deploy Dev
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build
      # Deploy to Dev Environment

  # Deploy Prod Job
  deploy-prod:
    name: Deploy Prod
    environment: prod
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    if: github.event_name != 'pull_request'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
